import { League_Spartan } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/navbar";
import Footer from "@/components/footer/footer";

const spartan = League_Spartan({
  subsets: ["latin"],
  weight: ["500", "600", "700"],
  style: ["normal"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={spartan.className}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
